services:
  mongodb:
    image: mongo
    container_name: mongo_chat
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ameda
      - MONGO_INITDB_ROOT_PASSWORD=ameda

  mongo-express:
    image: mongo-express
    container_name: mongo_express_chat
    restart: always
    ports:
      - 8581:8581
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=ameda
      - ME_CONFIG_MONGODB_ADMINPASSWORD=ameda
      - ME_CONFIG_MONGODB_SERVER=mongo_chat

volumes:
  mongo: {}